# Generated by Django 5.1.6 on 2025-05-07 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='procurementrequest',
            name='department',
        ),
        migrations.RemoveField(
            model_name='procurementrequest',
            name='requester',
        ),
        migrations.RemoveField(
            model_name='procurementrequest',
            name='vendor',
        ),
        migrations.DeleteModel(
            name='Department',
        ),
        migrations.DeleteModel(
            name='ProcurementRequest',
        ),
        migrations.DeleteModel(
            name='Vendor',
        ),
    ]
