# Generated by Django 5.1.6 on 2025-05-07 15:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_remove_procurementrequest_department_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('budget', models.DecimalField(decimal_places=2, max_digits=12)),
                ('remaining_budget', models.DecimalField(decimal_places=2, max_digits=12)),
            ],
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('contact_number', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='FinanceUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_approver', models.BooleanField(default=False)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.department')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProcurementRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('IT Equipment', 'IT Equipment'), ('Office Supplies', 'Office Supplies')], max_length=50)),
                ('item_name', models.CharField(max_length=100)),
                ('quantity', models.IntegerField()),
                ('cost_per_item', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=12)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('Pending Department Approval', 'Pending Department Approval'), ('Rejected by Department', 'Rejected by Department'), ('Pending Finance Approval', 'Pending Finance Approval'), ('Rejected by Finance', 'Rejected by Finance'), ('PO Generated', 'PO Generated'), ('Fulfilled', 'Fulfilled')], default='Pending Department Approval', max_length=50)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.department')),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OfficeSupplyDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preferred_brand', models.CharField(max_length=100)),
                ('request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.procurementrequest')),
            ],
        ),
        migrations.CreateModel(
            name='ITEquipmentDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('warrenty_period', models.CharField(max_length=50)),
                ('technical_specifications', models.TextField()),
                ('request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.procurementrequest')),
            ],
        ),
    ]
