# Generated by Django 5.1.6 on 2025-05-07 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='remaining_budget',
        ),
    ]
