# Generated by Django 5.1.6 on 2025-05-07 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_department_remaining_budget'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='officesupplydetails',
            name='request',
        ),
        migrations.DeleteModel(
            name='ITEquipmentDetails',
        ),
        migrations.DeleteModel(
            name='OfficeSupplyDetails',
        ),
    ]
