# Generated by Django 5.1.6 on 2025-05-07 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_itequipmentdetails_officesupplydetails'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='officesupplydetails',
            name='request',
        ),
        migrations.RemoveField(
            model_name='procurementrequest',
            name='cost_per_item',
        ),
        migrations.RemoveField(
            model_name='procurementrequest',
            name='item_name',
        ),
        migrations.DeleteModel(
            name='ITEquipmentDetails',
        ),
        migrations.DeleteModel(
            name='OfficeSupplyDetails',
        ),
    ]
