# Generated by Django 5.1.6 on 2025-05-07 16:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_officesupplydetails_request_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ITEquipmentDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('warranty_period', models.CharField(max_length=50)),
                ('technical_specifications', models.TextField()),
                ('cost_per_item', models.DecimalField(decimal_places=2, max_digits=10)),
                ('request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.procurementrequest')),
            ],
        ),
        migrations.CreateModel(
            name='OfficeSupplyDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('preferred_brand', models.CharField(max_length=100)),
                ('cost_per_item', models.DecimalField(decimal_places=2, max_digits=10)),
                ('request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.procurementrequest')),
            ],
        ),
    ]
