# Generated by Django 5.1.6 on 2025-05-07 20:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_remove_itequipmentdetails_request_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='procurementrequest',
            name='equipment',
        ),
        migrations.AddField(
            model_name='procurementrequest',
            name='it_equipment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.itequipmentdetails'),
        ),
        migrations.AddField(
            model_name='procurementrequest',
            name='office_supply',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.officesupplydetails'),
        ),
    ]
