# Generated by Django 5.1.6 on 2025-05-07 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_remove_procurementrequest_equipment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='procurementrequest',
            name='requester',
            field=models.CharField(max_length=100),
        ),
    ]
