# Generated by Django 5.1.6 on 2025-05-08 00:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_procurementrequest_requester'),
    ]

    operations = [
        migrations.AlterField(
            model_name='procurementrequest',
            name='status',
            field=models.CharField(choices=[('Pending Department Approval', 'Pending Department Approval'), ('Rejected by Department', 'Rejected by Department'), ('Pending Finance Approval', 'Pending Finance Approval'), ('Approved by Finance', 'Approved by Finance'), ('Rejected by Finance', 'Rejected by Finance'), ('PO Generated', 'PO Generated'), ('Fulfilled', 'Fulfilled')], default='Pending Department Approval', max_length=50),
        ),
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('po_number', models.CharField(max_length=50)),
                ('total_cost', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(default='PO Generated', max_length=50)),
                ('issued_at', models.DateTimeField(auto_now_add=True)),
                ('fulfilled_at', models.DateTimeField(blank=True, null=True)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.procurementrequest')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.vendor')),
            ],
        ),
    ]
