# Generated by Django 5.1.6 on 2025-05-08 04:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_procurementrequest_status_purchaseorder'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchaseorder',
            name='status',
        ),
    ]
