# Generated by Django 5.1.6 on 2025-05-08 05:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_remove_purchaseorder_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='procurementrequest',
            name='vendor',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='core.vendor'),
            preserve_default=False,
        ),
    ]
