# Generated by Django 5.1.6 on 2025-05-08 05:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_procurementrequest_vendor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='procurementrequest',
            name='vendor',
        ),
    ]
