# Generated by Django 5.1.6 on 2025-05-08 05:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_remove_procurementrequest_vendor'),
    ]

    operations = [
        migrations.AddField(
            model_name='procurementrequest',
            name='vendor',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='core.vendor'),
            preserve_default=False,
        ),
    ]
